name: mobilecode
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.1.0 
   # cloud_firestore: 3.1.18  //dont use this for some reason it is really slow github fix??
  cloud_firestore: ^4.0.3
   #firebase_auth: 3.5.0
   #firebase_auth_platform_interface
  firebase_auth: ^4.0.2
  google_sign_in: 5.3.3
  sign_in_with_apple: 4.0.0
  crypto: ^3.0.2
  font_awesome_flutter: ^10.2.1
  google_fonts: 3.0.1
  provider: ^6.0.4
  rxdart: 0.27.4
  json_annotation: 4.5.0
  lottie: 1.2.1
  curved_navigation_bar: 1.0.3
  url_launcher: ^6.1.7
  mailto: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  build_runner: 2.1.11
  json_serializable: 6.2.0

flutter_icons:
    android: true

    ios: true
    image_path: "assets/app_logo.png"
    remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/covers/
  - assets/rocket.json
  - assets/no_good.json